# coding: utf-8

"""
UbiOps

Client Library to interact with the UbiOps API.

The version of the OpenAPI document: v2
Generated by: https://openapi-generator.tech
"""

import pprint


class EnvironmentTagCreate(object):
    """
    NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name and the value is attribute type
      attribute_map (dict): The key is attribute name and the value is json key in definition
    """

    openapi_types = {"name": "str", "status": "str", "supports_request_format": "bool"}

    attribute_map = {"name": "name", "status": "status", "supports_request_format": "supports_request_format"}

    def __init__(self, name=None, status=None, supports_request_format=None, **kwargs):
        """
        EnvironmentTagCreate - a model defined in OpenAPI
        """

        self.client_side_validation = True
        if "local_vars_configuration" in kwargs and kwargs["local_vars_configuration"] is not None:
            self.client_side_validation = kwargs["local_vars_configuration"].client_side_validation

        self._name = None
        self._status = None
        self._supports_request_format = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if status is not None:
            self.status = status
        if supports_request_format is not None:
            self.supports_request_format = supports_request_format

    @property
    def name(self):
        """
        Gets the name of this EnvironmentTagCreate

        :return: the name of this EnvironmentTagCreate
        :rtype: str
        """

        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this EnvironmentTagCreate

        :param name: the name of this EnvironmentTagCreate
        :type: str
        """

        if self.client_side_validation and (name is not None and not isinstance(name, str)):
            raise ValueError("Parameter `name` must be a string")

        if self.client_side_validation and (name is not None and len(name) > 128):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `128`")
        if self.client_side_validation and (name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")

        self._name = name

    @property
    def status(self):
        """
        Gets the status of this EnvironmentTagCreate

        :return: the status of this EnvironmentTagCreate
        :rtype: str
        """

        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this EnvironmentTagCreate

        :param status: the status of this EnvironmentTagCreate
        :type: str
        """

        if self.client_side_validation and (status is not None and not isinstance(status, str)):
            raise ValueError("Parameter `status` must be a string")

        self._status = status

    @property
    def supports_request_format(self):
        """
        Gets the supports_request_format of this EnvironmentTagCreate

        :return: the supports_request_format of this EnvironmentTagCreate
        :rtype: bool
        """

        return self._supports_request_format

    @supports_request_format.setter
    def supports_request_format(self, supports_request_format):
        """
        Sets the supports_request_format of this EnvironmentTagCreate

        :param supports_request_format: the supports_request_format of this EnvironmentTagCreate
        :type: bool
        """

        if self.client_side_validation and (
            supports_request_format is not None and not isinstance(supports_request_format, bool)
        ):
            raise ValueError("Parameter `supports_request_format` must be a boolean")

        self._supports_request_format = supports_request_format

    def to_dict(self):
        """
        Returns the model properties as a dict
        """

        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """

        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """

        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """

        if not isinstance(other, EnvironmentTagCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """

        if not isinstance(other, EnvironmentTagCreate):
            return True

        return self.to_dict() != other.to_dict()
