# coding: utf-8

"""
UbiOps

Client Library to interact with the UbiOps API.

The version of the OpenAPI document: v2
Generated by: https://openapi-generator.tech
"""

import pprint


class UserDetail(object):
    """
    NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name and the value is attribute type
      attribute_map (dict): The key is attribute name and the value is json key in definition
    """

    openapi_types = {
        "id": "str",
        "email": "str",
        "name": "str",
        "surname": "str",
        "registration_date": "datetime",
        "authentication": "str",
    }

    attribute_map = {
        "id": "id",
        "email": "email",
        "name": "name",
        "surname": "surname",
        "registration_date": "registration_date",
        "authentication": "authentication",
    }

    def __init__(
        self, id=None, email=None, name=None, surname=None, registration_date=None, authentication=None, **kwargs
    ):
        """
        UserDetail - a model defined in OpenAPI
        """

        self.client_side_validation = True
        if "local_vars_configuration" in kwargs and kwargs["local_vars_configuration"] is not None:
            self.client_side_validation = kwargs["local_vars_configuration"].client_side_validation

        self._id = None
        self._email = None
        self._name = None
        self._surname = None
        self._registration_date = None
        self._authentication = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.email = email
        if name is not None:
            self.name = name
        if surname is not None:
            self.surname = surname
        if registration_date is not None:
            self.registration_date = registration_date
        self.authentication = authentication

    @property
    def id(self):
        """
        Gets the id of this UserDetail

        :return: the id of this UserDetail
        :rtype: str
        """

        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this UserDetail

        :param id: the id of this UserDetail
        :type: str
        """

        if self.client_side_validation and (id is not None and not isinstance(id, str)):
            raise ValueError("Parameter `id` must be a string")

        self._id = id

    @property
    def email(self):
        """
        Gets the email of this UserDetail

        :return: the email of this UserDetail
        :rtype: str
        """

        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this UserDetail

        :param email: the email of this UserDetail
        :type: str
        """

        if self.client_side_validation and email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")
        if self.client_side_validation and (email is not None and not isinstance(email, str)):
            raise ValueError("Parameter `email` must be a string")

        if self.client_side_validation and (email is not None and len(email) > 254):
            raise ValueError("Invalid value for `email`, length must be less than or equal to `254`")
        if self.client_side_validation and (email is not None and len(email) < 1):
            raise ValueError("Invalid value for `email`, length must be greater than or equal to `1`")

        self._email = email

    @property
    def name(self):
        """
        Gets the name of this UserDetail

        :return: the name of this UserDetail
        :rtype: str
        """

        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this UserDetail

        :param name: the name of this UserDetail
        :type: str
        """

        if self.client_side_validation and (name is not None and not isinstance(name, str)):
            raise ValueError("Parameter `name` must be a string")

        if self.client_side_validation and (name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")

        self._name = name

    @property
    def surname(self):
        """
        Gets the surname of this UserDetail

        :return: the surname of this UserDetail
        :rtype: str
        """

        return self._surname

    @surname.setter
    def surname(self, surname):
        """
        Sets the surname of this UserDetail

        :param surname: the surname of this UserDetail
        :type: str
        """

        if self.client_side_validation and (surname is not None and not isinstance(surname, str)):
            raise ValueError("Parameter `surname` must be a string")

        if self.client_side_validation and (surname is not None and len(surname) < 1):
            raise ValueError("Invalid value for `surname`, length must be greater than or equal to `1`")

        self._surname = surname

    @property
    def registration_date(self):
        """
        Gets the registration_date of this UserDetail

        :return: the registration_date of this UserDetail
        :rtype: datetime
        """

        return self._registration_date

    @registration_date.setter
    def registration_date(self, registration_date):
        """
        Sets the registration_date of this UserDetail

        :param registration_date: the registration_date of this UserDetail
        :type: datetime
        """

        self._registration_date = registration_date

    @property
    def authentication(self):
        """
        Gets the authentication of this UserDetail

        :return: the authentication of this UserDetail
        :rtype: str
        """

        return self._authentication

    @authentication.setter
    def authentication(self, authentication):
        """
        Sets the authentication of this UserDetail

        :param authentication: the authentication of this UserDetail
        :type: str
        """

        if self.client_side_validation and authentication is None:
            raise ValueError("Invalid value for `authentication`, must not be `None`")
        if self.client_side_validation and (authentication is not None and not isinstance(authentication, str)):
            raise ValueError("Parameter `authentication` must be a string")

        if self.client_side_validation and (authentication is not None and len(authentication) < 1):
            raise ValueError("Invalid value for `authentication`, length must be greater than or equal to `1`")

        self._authentication = authentication

    def to_dict(self):
        """
        Returns the model properties as a dict
        """

        result = {}

        for attr, _ in self.openapi_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """

        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """

        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """

        if not isinstance(other, UserDetail):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """

        if not isinstance(other, UserDetail):
            return True

        return self.to_dict() != other.to_dict()
